name: YouTube Playlist

on:
  schedule:
    # Runs every hour, on the hour
    - cron: '1 * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest YT videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # comma-separated list of RSS feed urls
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCfLweXOMiUVt0VUfBax1cRw"
